manifest:
  remotes:
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: ovandongen
      url-base: https://github.com/ovandongen
  projects:
    - name: zmk
      remote: moergo-sc
      revision: main
      import: app/west.yml
    - name: zmk-hid-viz
      remote: ovandongen
      revision: main
  self:
    path: config